//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionaMelon
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class alumno
    {
        public alumno()
        {
            this.vista = new HashSet<vista>();
        }
    
        public int id_alumno { get; set; }
        [Display(Name = "Nombre")]
        [Required]
        [StringLength(50, ErrorMessage = "Debe tener como máximo 50 caracteres")]
        public string nombre { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "Debe tener como máximo 50 caracteres")]
        [Display(Name = "Apellido")]
        public string apellido { get; set; }
        [Display(Name = "Telefono")]
        [Required]
        [StringLength(50, ErrorMessage = "Debe tener como máximo 50 caracteres")]
        public string telefono { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "Debe tener como máximo 50 caracteres")]
        [Display(Name = "E-mail")]
        public string mail { get; set; }
        [Required]
        
        [Display(Name = "Curso")]
        public Nullable<int> fk_id_curso { get; set; }
        [Display(Name = "Netbook")]
        
        public Nullable<int> fk_id_netbook { get; set; }
        [Display(Name = "DNI")]
        [Required]
        [StringLength(10, ErrorMessage = "Debe tener como máximo 10 caracteres")]
        public string dni { get; set; }
    
        public virtual CursosT CursosT { get; set; }
        public virtual netbook netbook { get; set; }
        public virtual ICollection<vista> vista { get; set; }
    }
}
