//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionaMelon
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CursosT
    {
        public CursosT()
        {
            this.alumno = new HashSet<alumno>();
        }
    
        public int id_cursos { get; set; }
        [Display(Name = "Curso")]
        [Required]
        [StringLength(10, ErrorMessage = "Debe tener como máximo 10 caracteres")]
        public string cursos_descripcion { get; set; }
    
        public virtual ICollection<alumno> alumno { get; set; }
    }
}
