//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionaMelon
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class estadoGarantia
    {
        public estadoGarantia()
        {
            this.garantia = new HashSet<garantia>();
        }
    
        public int id_estado_garantia { get; set; }
        [Display(Name = "Estado en garantía")]
        [Required]
        [StringLength(50, ErrorMessage = "Debe tener como máximo 50 caracteres")]
        public string descripcion { get; set; }
    
        public virtual ICollection<garantia> garantia { get; set; }
    }
}
