//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionaMelon
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class garantia
    {
        public int idGarantia { get; set; }
        public Nullable<int> idVista { get; set; }
        [Display(Name = "Estado de garantía")]
        public Nullable<int> estadoGarantia { get; set; }
        [Display(Name = "Problema")]
        public Nullable<int> problema { get; set; }
        [Display(Name = "Comentarios")]
        public string comentarios { get; set; }
        [Display(Name = "Fecha de ingreso")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        [Display(Name = "Ticket")]
        public string ticket { get; set; }
        [Display(Name = "¿Retirada?")]
        public Nullable<bool> flagRetirada { get; set; }
        [Display(Name = "Fecha retirada")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> fechaRetirada { get; set; }
        [Display(Name = "¿Volvió?")]
        public Nullable<bool> flagVuelta { get; set; }
        [Display(Name = "Fecha vuelta")]
        public Nullable<System.DateTime> fechaVuelta { get; set; }
        public Nullable<bool> eliminado { get; set; }
    
        public virtual estadoGarantia estadoGarantia1 { get; set; }
        public virtual vista vista { get; set; }
        public virtual problema problema1 { get; set; }
    }
}
