//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionaMelon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestionaMelonBDDEntities : DbContext
    {
        public gestionaMelonBDDEntities()
            : base("name=gestionaMelonBDDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<estadoGarantia> estadoGarantia { get; set; }
        public virtual DbSet<garantia> garantia { get; set; }
        public virtual DbSet<problema> problema { get; set; }
        public virtual DbSet<vista> vista { get; set; }
        public virtual DbSet<reclamo> reclamo { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CursosT> CursosT { get; set; }
        public virtual DbSet<alumno> alumno { get; set; }
        public virtual DbSet<netbook> netbook { get; set; }
        public virtual DbSet<vista_usuario_reclamo> vista_usuario_reclamo { get; set; }
        public virtual DbSet<propUser> propUser { get; set; }
    }
}
