//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionaMelon
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class netbook
    {
        public netbook()
        {
            this.alumno = new HashSet<alumno>();
        }
    
        public int id_netbook { get; set; }
        [Display(Name = "N° de serie")]
        [Required]
        [StringLength(20, ErrorMessage = "Debe tener como máximo 20 caracteres")]
        public string ndeserie { get; set; }
        [Display(Name = "Marca")]
        [Required]
        [StringLength(50, ErrorMessage = "Debe tener como máximo 50 caracteres")]
        public string marca { get; set; }
        [Display(Name = "Modelo")]
        [Required]
        [StringLength(50, ErrorMessage = "Debe tener como máximo 50 caracteres")]
        public string modelo { get; set; }
    
        public virtual ICollection<alumno> alumno { get; set; }
    }
}
