//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionaMelon
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class propUser
    {
        public int id { get; set; }
        [Display(Name = "E-mail")]
        public string mail { get; set; }
        public string fk_id_user { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
