//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionaMelon
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class reclamo
    {
        public reclamo()
        {
            this.vista_usuario_reclamo = new HashSet<vista_usuario_reclamo>();
        }
    
        public int id_reclamo { get; set; }
        [Display(Name = "Reclamo")]
        [Required(ErrorMessage = "Escriba aqui su comentario o reclamo")]
        [StringLength(300, ErrorMessage = "Debe tener como máximo 300 caracteres")]
        public string descripcion { get; set; }
    
        public virtual ICollection<vista_usuario_reclamo> vista_usuario_reclamo { get; set; }
    }
}
