//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionaMelon
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class vista_usuario_reclamo
    {
        public int id_vista_usuario_reclamo { get; set; }
        public string id_usuario { get; set; }
        public Nullable<int> id_reclamo { get; set; }
        public Nullable<int> id_vista { get; set; }
        public Nullable<bool> visto { get; set; }

        
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name="Fecha")]
        public Nullable<System.DateTime> fecha { get; set; }
        public string id_usuario_destino { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual reclamo reclamo { get; set; }
        public virtual vista vista { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
