//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionaMelon
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class vista
    {
        public vista()
        {
            this.garantia = new HashSet<garantia>();
            this.vista_usuario_reclamo = new HashSet<vista_usuario_reclamo>();
        }
    
        public int idVista { get; set; }
        [Display(Name = "N° de serie")]
        public string ndeserie { get; set; }
        [Display(Name = "Alumno")]
        public string alumno { get; set; }
        [Display(Name = "Estado")]
        public Nullable<int> fk_estado { get; set; }
        [Display(Name = "Comentarios")]
        public string comentarios { get; set; }
        [Display(Name = "Fecha ingreso")]

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        [Display(Name = "¿Retirada?")]
        public Nullable<bool> flagRetirada { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "Fecha retirada")]
        public Nullable<System.DateTime> fechaRetirada { get; set; }
        [Display(Name = "Alumno")]
        public Nullable<int> fk_id_alumno { get; set; }
        public Nullable<bool> eliminado { get; set; }
        [Display(Name = "Estado")]
        public virtual estado estado { get; set; }
        public virtual ICollection<garantia> garantia { get; set; }
        public virtual alumno alumno1 { get; set; }
        public virtual ICollection<vista_usuario_reclamo> vista_usuario_reclamo { get; set; }
    }
}
